apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine
spec:
  containers:
  - name: alpine-container
    #image: alpine:latest
    #command: ["sh", "-c", "while true; do echo Hello from Alpine!; sleep 5; done"]
    image: rclone/rclone:master
    command: ["rclone", "--stats-one-line", "--stats", "2s", "-vv", "--progress", "copy", "minio:/api-metrics", "swfs:/api-metrics"]
    # args:
    #   - --stats-one-line --stats 2s
    #   - copy
    #   - swfs:/api-metrics
    #   - minio:/api-metrics
    volumeMounts:
          - mountPath: /config/rclone/rclone.conf
            name: data-copy-config
            subPath: rclone.config
    resources:
      requests:
        memory: 4Gi
      limits:
        memory: 4Gi
  volumes:
      - configMap:
          #defaultMode: 777
          items:
          - key: rclone.config
            #mode: 777
            path: rclone.config
          name: data-copy-config
          optional: false
        name: data-copy-config