apiVersion: v1
kind: ConfigMap
metadata:
  name: data-copy-config
  labels:
    app: seaweedfs
    # chart: {{ template "druid.chart" . }}
    # release: {{ .Release.Name }}
    # heritage: {{ .Release.Service }}
data:
  rclone.config: |-
    [swfs]
    type = s3
    provider = SeaweedFS
    access_key_id = 3gjYN0fXUV
    secret_access_key = ohiWWEOBb77qf1Zlk9jqWqXfN92nUmpGUxC9rzyd
    endpoint = seaweedfs-s3:8333
    acl = public-read

    [minio]
    type = s3
    provider = Minio
    access_key_id = 3gjYN0fXUV
    secret_access_key = ohiWWEOBb77qf1Zlk9jqWqXfN92nUmpGUxC9rzyd
    endpoint = minio:9000
    acl = public-read